spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: localhost:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch_lgc
      cluster-nodes: localhost:9300
  mail:
    username: ceryss@126.com
    password: ceryss126
    host: smtp.126.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/lgc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    devtools: Chang0.com
      restart:
        additional-paths: 'src/main/java'
        enabled: 'true'
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  config: classpath:logback-spring.xml