/*
 * This file is generated by jOOQ.
 */
package com.aladdin.data.entity.auto;


import com.aladdin.data.entity.auto.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in data
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>data.user</code>.
     */
    public static final User USER = User.USER;
}
