spring:
  application:
    name: nacos-provider-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        incloude: "*"
