spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: localhost:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch_lgc
      cluster-nodes: localhost:9300

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"