server:
  port: 9101
dubbo:
  application:
    name: provider-dubbo
  registry:
    address: zookeeper://192.168.1.102:2181
  scan:
    base-packages: com.aladdin.bootdubbo.service.dubbo

  protocol: zookeeper
